# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mercury.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mercury.proto',
  package='mercury',
  serialized_pb='\n\rmercury.proto\x12\x07mercury\"\xfa\x03\n\x0eMercuryMessage\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12-\n\x04type\x18\x02 \x01(\x0e\x32\x1f.mercury.MercuryMessage.MsgType\x12\x31\n\x08src_addr\x18\x03 \x01(\x0b\x32\x1f.mercury.MercuryMessage.Address\x12\x31\n\x08\x64st_addr\x18\x04 \x01(\x0b\x32\x1f.mercury.MercuryMessage.Address\x12(\n\x0bsession_msg\x18\x05 \x01(\x0b\x32\x13.mercury.SessionMsg\x12&\n\npubsub_msg\x18\x06 \x01(\x0b\x32\x12.mercury.PubSubMsg\x1aZ\n\x07\x41\x64\x64ress\x12.\n\x04type\x18\x01 \x01(\x0e\x32 .mercury.MercuryMessage.AddrType\x12\x0e\n\x06\x63li_id\x18\x02 \x01(\x03\x12\x0f\n\x07geo_mat\x18\x03 \x01(\t\"]\n\x07MsgType\x12\x0b\n\x07\x41\x44_SESS\x10\x01\x12\x0b\n\x07PUB_CLI\x10\x02\x12\x0c\n\x08\x43LI_SESS\x10\x03\x12\x0e\n\nCLI_SUBSCR\x10\x04\x12\r\n\tCLI_UNSUB\x10\x05\x12\x0b\n\x07\x43LI_PUB\x10\x06\"8\n\x08\x41\x64\x64rType\x12\n\n\x06\x43LIENT\x10\x01\x12\x0b\n\x07\x41\x44\x41PTER\x10\x02\x12\n\n\x06PUBSUB\x10\x03\x12\x07\n\x03GEO\x10\x04\"\xcb\x01\n\nSessionMsg\x12\n\n\x02id\x18\x01 \x01(\x05\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x1b.mercury.SessionMsg.MsgType\x12.\n\nattributes\x18\x03 \x03(\x0b\x32\x1a.mercury.SessionMsg.KeyVal\x1a\"\n\x06KeyVal\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\t\"2\n\x07MsgType\x12\x08\n\x04INIT\x10\x01\x12\t\n\x05\x43LOSE\x10\x02\x12\n\n\x06\x43LIREP\x10\x03\x12\x06\n\x02HB\x10\x04\"m\n\tPubSubMsg\x12\r\n\x05topic\x18\x01 \x01(\t\x12-\n\nattributes\x18\x02 \x03(\x0b\x32\x19.mercury.PubSubMsg.KeyVal\x1a\"\n\x06KeyVal\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\t')



_MERCURYMESSAGE_MSGTYPE = _descriptor.EnumDescriptor(
  name='MsgType',
  full_name='mercury.MercuryMessage.MsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AD_SESS', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUB_CLI', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLI_SESS', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLI_SUBSCR', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLI_UNSUB', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLI_PUB', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=382,
  serialized_end=475,
)

_MERCURYMESSAGE_ADDRTYPE = _descriptor.EnumDescriptor(
  name='AddrType',
  full_name='mercury.MercuryMessage.AddrType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLIENT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADAPTER', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUBSUB', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEO', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=477,
  serialized_end=533,
)

_SESSIONMSG_MSGTYPE = _descriptor.EnumDescriptor(
  name='MsgType',
  full_name='mercury.SessionMsg.MsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INIT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLIREP', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HB', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=689,
  serialized_end=739,
)


_MERCURYMESSAGE_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='mercury.MercuryMessage.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mercury.MercuryMessage.Address.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cli_id', full_name='mercury.MercuryMessage.Address.cli_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='geo_mat', full_name='mercury.MercuryMessage.Address.geo_mat', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=290,
  serialized_end=380,
)

_MERCURYMESSAGE = _descriptor.Descriptor(
  name='MercuryMessage',
  full_name='mercury.MercuryMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='mercury.MercuryMessage.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='mercury.MercuryMessage.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_addr', full_name='mercury.MercuryMessage.src_addr', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dst_addr', full_name='mercury.MercuryMessage.dst_addr', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session_msg', full_name='mercury.MercuryMessage.session_msg', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pubsub_msg', full_name='mercury.MercuryMessage.pubsub_msg', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MERCURYMESSAGE_ADDRESS, ],
  enum_types=[
    _MERCURYMESSAGE_MSGTYPE,
    _MERCURYMESSAGE_ADDRTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=533,
)


_SESSIONMSG_KEYVAL = _descriptor.Descriptor(
  name='KeyVal',
  full_name='mercury.SessionMsg.KeyVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mercury.SessionMsg.KeyVal.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='mercury.SessionMsg.KeyVal.val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=653,
  serialized_end=687,
)

_SESSIONMSG = _descriptor.Descriptor(
  name='SessionMsg',
  full_name='mercury.SessionMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mercury.SessionMsg.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='mercury.SessionMsg.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='mercury.SessionMsg.attributes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SESSIONMSG_KEYVAL, ],
  enum_types=[
    _SESSIONMSG_MSGTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=536,
  serialized_end=739,
)


_PUBSUBMSG_KEYVAL = _descriptor.Descriptor(
  name='KeyVal',
  full_name='mercury.PubSubMsg.KeyVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mercury.PubSubMsg.KeyVal.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='mercury.PubSubMsg.KeyVal.val', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=653,
  serialized_end=687,
)

_PUBSUBMSG = _descriptor.Descriptor(
  name='PubSubMsg',
  full_name='mercury.PubSubMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='mercury.PubSubMsg.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='mercury.PubSubMsg.attributes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_PUBSUBMSG_KEYVAL, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=741,
  serialized_end=850,
)

_MERCURYMESSAGE_ADDRESS.fields_by_name['type'].enum_type = _MERCURYMESSAGE_ADDRTYPE
_MERCURYMESSAGE_ADDRESS.containing_type = _MERCURYMESSAGE;
_MERCURYMESSAGE.fields_by_name['type'].enum_type = _MERCURYMESSAGE_MSGTYPE
_MERCURYMESSAGE.fields_by_name['src_addr'].message_type = _MERCURYMESSAGE_ADDRESS
_MERCURYMESSAGE.fields_by_name['dst_addr'].message_type = _MERCURYMESSAGE_ADDRESS
_MERCURYMESSAGE.fields_by_name['session_msg'].message_type = _SESSIONMSG
_MERCURYMESSAGE.fields_by_name['pubsub_msg'].message_type = _PUBSUBMSG
_MERCURYMESSAGE_MSGTYPE.containing_type = _MERCURYMESSAGE;
_MERCURYMESSAGE_ADDRTYPE.containing_type = _MERCURYMESSAGE;
_SESSIONMSG_KEYVAL.containing_type = _SESSIONMSG;
_SESSIONMSG.fields_by_name['type'].enum_type = _SESSIONMSG_MSGTYPE
_SESSIONMSG.fields_by_name['attributes'].message_type = _SESSIONMSG_KEYVAL
_SESSIONMSG_MSGTYPE.containing_type = _SESSIONMSG;
_PUBSUBMSG_KEYVAL.containing_type = _PUBSUBMSG;
_PUBSUBMSG.fields_by_name['attributes'].message_type = _PUBSUBMSG_KEYVAL
DESCRIPTOR.message_types_by_name['MercuryMessage'] = _MERCURYMESSAGE
DESCRIPTOR.message_types_by_name['SessionMsg'] = _SESSIONMSG
DESCRIPTOR.message_types_by_name['PubSubMsg'] = _PUBSUBMSG

class MercuryMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Address(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MERCURYMESSAGE_ADDRESS

    # @@protoc_insertion_point(class_scope:mercury.MercuryMessage.Address)
  DESCRIPTOR = _MERCURYMESSAGE

  # @@protoc_insertion_point(class_scope:mercury.MercuryMessage)

class SessionMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class KeyVal(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SESSIONMSG_KEYVAL

    # @@protoc_insertion_point(class_scope:mercury.SessionMsg.KeyVal)
  DESCRIPTOR = _SESSIONMSG

  # @@protoc_insertion_point(class_scope:mercury.SessionMsg)

class PubSubMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class KeyVal(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PUBSUBMSG_KEYVAL

    # @@protoc_insertion_point(class_scope:mercury.PubSubMsg.KeyVal)
  DESCRIPTOR = _PUBSUBMSG

  # @@protoc_insertion_point(class_scope:mercury.PubSubMsg)


# @@protoc_insertion_point(module_scope)
